[default.general]
chip = "STM32F446RETx"

[default.reset]
# Whether or not the target should be halted after reset.
halt_afterwards = true

[default.gdb]
# Whether or not a GDB server should be opened after flashing.
# This is exclusive and cannot be used with RTT at the moment.
enabled = true
